/**
 * The request id: one opaque value per HTTP request, generated by us or echoed
 * from a well-formed inbound header.
 *
 * WHY IT EXISTS. `correlation_id` used to be minted inside `jsonError`, once per
 * ERROR RESPONSE (src/lib/http.ts). That made it a property of a body, not of a
 * request: two errors in one request got two ids, no other log line of the same
 * request could carry it, and a user's report could not be joined to anything.
 * This module holds the identity rules; src/lib/request-context.ts makes the id
 * ambient for the duration of a request.
 *
 * WHY THE HEADER IS *VALIDATED* AND NOT JUST ACCEPTED. The id is written to log
 * lines and returned to the caller, so an unbounded, arbitrary inbound string is
 * an injection surface: a newline would forge a second line in the development
 * log format (`formatHuman` writes `${msg} key=value` through `console.error`,
 * whereas the production format's `JSON.stringify` would escape it), and an
 * oversized value would let a caller inflate every line about its request. A
 * malformed value is therefore DISCARDED and replaced — never echoed back, and
 * never logged — which is also what makes the value safe to treat as opaque.
 *
 * The module deliberately imports nothing (no `node:crypto`): src/proxy.ts runs
 * in the edge runtime, where Node built-ins are unavailable, exactly like the
 * reason documented in src/proxy.ts for not importing src/lib/env.ts. `randomUUID`
 * is taken from the global Web Crypto, which exists in every runtime this app
 * targets (Node ≥ 22 and the edge).
 */

/** The inbound/outbound request-id header. */
export const REQUEST_ID_HEADER = 'x-request-id';

/**
 * Well-formed = a bounded, log-safe, opaque token: 8–128 characters of
 * `[A-Za-z0-9._-]`. The charset is what makes the value safe to print in either
 * log format, and the bound keeps one caller from bloating the log.
 *
 * A uuid satisfies it, but so do the formats other proxies emit (`traceparent`
 * ids, `req-…` ids, ULIDs), so a caller or an upstream proxy can carry its own
 * id through rather than having it replaced.
 */
const WELL_FORMED_REQUEST_ID = /^[A-Za-z0-9._-]{8,128}$/;

/**
 * Two literal strings that pass the charset check but must still be rejected,
 * because they are what a caller sends when it has NO id: Go's `net/http` and
 * several HTTP clients stringify a missing value as `null`/`undefined`, and a JS
 * client interpolating an unset variable produces the same text.
 *
 * WHY REJECT THEM. They are log-safe, so this is not about injection — it is
 * about the one property an id has to have: being unique per request. Accepting
 * them would collapse every such caller into a single trace id, and a "trace"
 * that maps to thousands of requests is worse than no trace at all, because it
 * looks like an answer.
 */
const SENTINEL_REQUEST_IDS = new Set(['null', 'undefined']);

/** True when `value` may be reused as a request id (narrows to `string`). */
export function isWellFormedRequestId(value: string | null | undefined): value is string {
  if (typeof value !== 'string') return false;
  if (SENTINEL_REQUEST_IDS.has(value.toLowerCase())) return false;
  return WELL_FORMED_REQUEST_ID.test(value);
}

/** A fresh, opaque request id. */
export function newRequestId(): string {
  return globalThis.crypto.randomUUID();
}

/**
 * The id for one request: the caller's own when it is well-formed, otherwise a
 * new one. This is the single decision point for "reuse or generate", so the
 * proxy (header normalisation) and the route wrapper (context seeding) cannot
 * disagree about it.
 */
export function resolveRequestId(incoming: string | null | undefined): string {
  return isWellFormedRequestId(incoming) ? incoming : newRequestId();
}
