/** Curated common IANA zones for the create-event form (UTC included).
 * The API validates via Intl; any valid zone still works via other tooling. */
export const COMMON_TIMEZONES: readonly string[] = [
  'UTC',
  'Europe/London',
  'Europe/Madrid',
  'Europe/Moscow',
  'Europe/Berlin',
  'Europe/Paris',
  'Europe/Lisbon',
  'Europe/Kyiv',
  'Europe/Istanbul',
  'Asia/Jerusalem',
  'Asia/Dubai',
  'Asia/Tbilisi',
  'Asia/Almaty',
  'Asia/Bangkok',
  'Asia/Singapore',
  'Asia/Shanghai',
  'Asia/Tokyo',
  'Asia/Kolkata',
  'Australia/Sydney',
  'America/New_York',
  'America/Toronto',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Mexico_City',
  'America/Sao_Paulo',
  'America/Buenos_Aires',
  'Africa/Cairo',
  'Africa/Lagos',
  'Pacific/Auckland',
];
