import test from 'node:test';
import assert from 'node:assert/strict';
import {scorePair,recommend,canRevealPrivate,normalTags,escapeVCard} from '../contracts/matching.mjs';
const a={id:'a',eligible:true,needs:['pilot'],offers:['design']};
const b={id:'b',eligible:true,needs:['design'],offers:['pilot']};
test('full complementary pair scores 100, not mutual consent',()=>{const m=scorePair(a,b);assert.equal(m.score,100);assert.equal(m.mutualConsent,false);});
test('score symmetry',()=>assert.equal(scorePair(a,b).score,scorePair(b,a).score));
test('reason direction swaps',()=>assert.deepEqual(scorePair(a,b).reasonsForA,scorePair(b,a).reasonsForB));
test('self excluded',()=>assert.equal(scorePair(a,a),null));
test('both seek same thing not complement',()=>assert.equal(scorePair(a,{...a,id:'z'}),null));
test('one sided match excluded',()=>assert.equal(scorePair(a,{...b,needs:['investor']}),null));
test('blocked excluded',()=>assert.equal(scorePair(a,{...b,blocked:true}),null));
test('eligibility not assumed',()=>assert.equal(scorePair(a,{...b,eligible:undefined}),null));
test('empty needs normal empty state',()=>assert.equal(scorePair({...a,needs:[]},b),null));
test('normalize duplicates case whitespace',()=>assert.deepEqual(normalTags([' Pilot ','pilot','']),['pilot']));
test('bad input rejected',()=>assert.throws(()=>normalTags([12]),TypeError));
test('partial relevance formula',()=>assert.equal(scorePair({...a,needs:['pilot','client']},b).score,60));
test('no padding to three',()=>assert.equal(recommend(a,[b]).length,1));
test('dedup candidates',()=>assert.equal(recommend(a,[b,b,b]).length,1));
test('limit top3',()=>assert.equal(recommend(a,['b','c','d','e'].map(id=>({...b,id}))).length,3));
test('stable tie break IDs',()=>assert.deepEqual(recommend(a,[{...b,id:'c'},b]).map(x=>x.id),['b','c']));
test('pending load tie break',()=>assert.equal(recommend(a,[{...b,id:'c'}, {...b,pending:2}])[0].id,'c'));
test('no private contact leakage in output',()=>assert.equal(JSON.stringify(recommend(a,[{...b,email:'private@example.com'}])).includes('private'),false));
test('one consent no private reveal',()=>assert.equal(canRevealPrivate({state:'mutually_accepted',aAccepted:true,bAccepted:false,consentVersion:1},{allowed:true,consentVersion:1}),false));
test('both consent and fresh policy allow reveal',()=>assert.equal(canRevealPrivate({state:'mutually_accepted',aAccepted:true,bAccepted:true,consentVersion:2},{allowed:true,consentVersion:2}),true));
test('revocation blocks reveal',()=>assert.equal(canRevealPrivate({state:'mutually_accepted',aAccepted:true,bAccepted:true,revoked:true,consentVersion:1},{allowed:true,consentVersion:1}),false));
test('stale policy blocks reveal',()=>assert.equal(canRevealPrivate({state:'mutually_accepted',aAccepted:true,bAccepted:true,consentVersion:1},{allowed:true,consentVersion:2}),false));
test('vCard CRLF escaped',()=>assert.equal(escapeVCard('A\r\nEMAIL:evil'), 'A\\nEMAIL:evil'));
test('vCard delimiters escaped',()=>assert.equal(escapeVCard('a,b;c\\d'),'a\\,b\\;c\\\\d'));
